In [47]:
import random as rd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import statistics as stat
import math

import pandas as pd 

data = pd.read_csv("SAheart.txt", sep = ',')

last_column_name = data.columns[-1]

0      1
1      1
2      0
3      1
4      1
      ..
457    0
458    1
459    0
460    0
461    1
Name: chd, Length: 462, dtype: int64


In [48]:
#The data

N=500 
xgauss1=[rd.gauss(0,1) for i in range(N)]
xgauss2=[rd.gauss(0,1) for i in range(N)]


In [67]:
#A labeled Data Set


#group I

mean_group_I = [2.5, 2.5]
cov_group_I = [[2.0, -0.8], [-0.8, 2.0]]

n1 = 100

group_I_data = np.random.multivariate_normal(mean_group_I, cov_group_I, n1)

labels_group_I = np.ones(n1)

mean_I = np.mean(group_I_data)
deviation_I = np.std(group_I_data)
correlation_matrix_group_I = np.corrcoef(group_I_data)

#group II

mean_group_II = [0.0, 0.0]
cov_group_II = [[1.0, 0.0], [0.0, 1.0]]

n2 = 200

group_II_data = np.random.multivariate_normal(mean_group_II, cov_group_II, n2)

labels_group_II = np.zeros(n2)

mean_II = np.mean(group_II_data)
deviation_II = np.std(group_II_data)
correlation_matrix_group_II = np.corrcoef(group_II_data)


[[ 1. -1. -1. ...  1. -1. -1.]
 [-1.  1.  1. ... -1.  1.  1.]
 [-1.  1.  1. ... -1.  1.  1.]
 ...
 [ 1. -1. -1. ...  1. -1. -1.]
 [-1.  1.  1. ... -1.  1.  1.]
 [-1.  1.  1. ... -1.  1.  1.]]


In [68]:
#x1 = xgauss1
#X2 = xgauss2

#Eval data
#x1_min, x1_max = min(x1), max(x1)
#x2_min, x2_max = min(x2), max(x2)
#Neval=15; h1= (x1_max-x1_min)/Neval; h2=(x2_max-x2_min)/Neval
#x1Eval, x2Eval= np.meshgrid(np.arange(x1_min, x1_max, h1), np.arange(x2_min, x2_max, h2));


A first model of machine learning. The naive Bayes model

Ici on écrit fk(x) = A*exp(B)

In [82]:


def prior_probability(data):
    
    X = last_column_name
    
    num = 0
    det = 0    
    
    for i in range(len(X)):
        if(X[i]==0):
            num += 1
            det +=1
            
        else: 
            det +=1
    
    return [num/det, 1-num/det]
    
    
    
def probability(x, mu, sigma, k):
    
    p = len(mu) 
    
    det = np.linalg.det(sigma)
    
    A = 1/((2*np.pi)^(p/2)*np.roots(det))
    
    B = -1/2*np.transpose(x-mu[k])*sigma[k]*np.linalg.inv()*(x-mu[k])
    

#def posterior_probability(data, p1, p2, n):
    
    
#def MAP():

data_I = data[data['chd']==0]
data_II = data[data['chd']==1]

real_data_mean_I = data_I.mean().values
real_data_mean_II = data_II.mean().values

real_correlation_matrix_group_I = data_I.corr().values
real_correlation_matrix_group_II = data_II.corr().values


def probability_I(x):
    p=len(x)
    
    A = 1/((2*np.pi)^(p/2)*np.roots(np.linalg.det(real_correlation_matrix_group_I))
    B = -1/2*
 
     

[[ 1.          0.13075771 -0.02863206 -0.06386361  0.03748544 -0.08687177
  -0.03238472  0.12949303 -0.00371992         nan]
 [ 0.13075771  1.          0.18372644  0.15433871  0.40948255 -0.0765106
   0.30746132  0.16764485  0.39707704         nan]
 [-0.02863206  0.18372644  1.          0.22959436  0.32909697  0.02091373
   0.1705976   0.19744797  0.46338492         nan]
 [-0.06386361  0.15433871  0.22959436  1.          0.40729153  0.00981056
   0.32158334  0.04105364  0.30947596         nan]
 [ 0.03748544  0.40948255  0.32909697  0.40729153  1.         -0.09124614
   0.71090911  0.2140987   0.66038871         nan]
 [-0.08687177 -0.0765106   0.02091373  0.00981056 -0.09124614  1.
   0.03391898  0.0901922  -0.12378813         nan]
 [-0.03238472  0.30746132  0.1705976   0.32158334  0.71090911  0.03391898
   1.          0.15153784  0.33775412         nan]
 [ 0.12949303  0.16764485  0.19744797  0.04105364  0.2140987   0.0901922
   0.15153784  1.          0.15290409         nan]
 [-0.00371